### ISSUE TITLE
Nejde nainstalovat

### ISSUE THREAD

**Issue by TomasZmek** [ogioncz/flarum-ext-czech#1]
po zadání
`composer require ogioncz/flarum-ext-czech`

vypisuje chybu 
```
 [InvalidArgumentException]
  Could not find a version of package ogioncz/flarum-ext-czech matching your minimum-stability (beta). Require it with an explicit version constraint allowing its d
  esired stability.
```
mám verzi beta8

**Comment by jtojnar** [comment]
Díky za upozornění, README není kompletní. 

Chyba říká jak to řešit: buď přidej do `composer.json` klíč [`"minimum-stability": "dev"`](https://getcomposer.org/doc/04-schema.md#minimum-stability) nebo lépe, explicitně zadej verzi při [instalaci](https://getcomposer.org/doc/03-cli.md#require): `composer require ogioncz/flarum-ext-czech:dev-master`

**Comment by Avskum** [comment]
> Díky za upozornění, README není kompletní.
> 
> Chyba říká jak to řešit: buď přidej do `composer.json` klíč [`"minimum-stability": "dev"`](https://getcomposer.org/doc/04-schema.md#minimum-stability) nebo lépe, explicitně zadej verzi při [instalaci](https://getcomposer.org/doc/03-cli.md#require): `composer require ogioncz/flarum-ext-czech:dev-master`

Mám stejný problém jako kolega výše. I při použití tvého příkazu k instalaci.

UPDATE: byl nutný reinstal composeru
